apiVersion: v1
kind: Pod
metadata:
  name: flask-test
  labels:
    app: flask-test
spec:
  containers:
    - name: flask-test
      image: gcr.io/simplebrs-dev/flask_test
      ports:
        - name: http
          containerPort: 8080
